"""empty message

Revision ID: 621b32132f09
Revises: 714256bfd26c
Create Date: 2023-09-25 14:39:16.282298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '621b32132f09'
down_revision = '714256bfd26c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('store_id')

    # ### Stores_app Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('store_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'stores', ['store_id'], ['id'])

    # ### Stores_app Alembic commands ###
